- hosts: all
  gather_facts: True
  tasks:
    - name: Disk space used
      shell: du -s /var/spool/*|sort -n
      register: disk_used
    - debug: var=disk_used
    - local_action: copy content="{{ disk_used }}" dest=./fact
    - local_action: shell cat fact|jq ".stdout_lines" >> facts_all
